# Generated by Django 3.0.8 on 2020-07-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='genres',
            new_name='genre',
        ),
    ]
