# Generated by Django 3.0.8 on 2020-07-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
